---

- name: Install Necessary Software
  hosts: all
  roles:
    -  role: common

- name: Setup Master node
  hosts: Type_Master
  roles:
    -  role: master

- name: Setup worker node
  hosts: Type_Worker
  roles:
    -  role: worker