---

- name: Install Necessary Software
  hosts: aws_ec2
  roles:
    -  role: common

- name: Setup Master node
  hosts: Tag_Type_Master
  roles:
    -  role: master

- name: Setup worker node
  hosts: Tag_Type_Worker
  roles:
    -  role: worker