---
# tasks file for worker
- name: Copy the join command to server location
  copy: 
    src: "../files/join-command" 
    dest: "/tmp/join-command.sh mode=0777"

- name: Join the node to cluster
  command: sh /tmp/join-command.sh