apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend 
    spec:
      containers:
      - name: node-backend
        image: nimnambi/backend:1.0
        ports:
        - containerPort: 3000
--- 

apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  selector:
    app: node-backend 
  type: NodePort
  ports:
  - protocol: TCP
    port: 31110
    targetPort: 3000
    nodePort: 31110